/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_firepick_firesight_FireSight */

#ifndef _Included_org_firepick_firesight_FireSight
#define _Included_org_firepick_firesight_FireSight
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_firepick_firesight_FireSight
 * Method:    process
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_firepick_firesight_FireSight_process
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
