/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_firepick_firesight_HoleRecognizer */

#ifndef _Included_org_firepick_firesight_HoleRecognizer
#define _Included_org_firepick_firesight_HoleRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_firepick_firesight_HoleRecognizer
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_firepick_firesight_HoleRecognizer_release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_firepick_firesight_HoleRecognizer
 * Method:    init
 * Signature: (FF)J
 */
JNIEXPORT jlong JNICALL Java_org_firepick_firesight_HoleRecognizer_init
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_firepick_firesight_HoleRecognizer
 * Method:    _showMatches
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_firepick_firesight_HoleRecognizer__1showMatches
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_firepick_firesight_HoleRecognizer
 * Method:    scan
 * Signature: (JJFF)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_firepick_firesight_HoleRecognizer_scan
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
