/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_firepick_firesight_HoughCircle */

#ifndef _Included_org_firepick_firesight_HoughCircle
#define _Included_org_firepick_firesight_HoughCircle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_firepick_firesight_HoughCircle
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_firepick_firesight_HoughCircle_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_firepick_firesight_HoughCircle
 * Method:    setShowCircles
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_firepick_firesight_HoughCircle_setShowCircles
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_firepick_firesight_HoughCircle
 * Method:    setFilterParams
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_firepick_firesight_HoughCircle_setFilterParams
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     org_firepick_firesight_HoughCircle
 * Method:    setHoughParams
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_firepick_firesight_HoughCircle_setHoughParams
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_firepick_firesight_HoughCircle
 * Method:    scan
 * Signature: (J)[Lorg/firepick/firesight/Circle;
 */
JNIEXPORT jobjectArray JNICALL Java_org_firepick_firesight_HoughCircle_scan
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_firepick_firesight_HoughCircle
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_firepick_firesight_HoughCircle_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
