/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_firepick_firesight_MatchedRegion */

#ifndef _Included_org_firepick_firesight_MatchedRegion
#define _Included_org_firepick_firesight_MatchedRegion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_firepick_firesight_MatchedRegion
 * Method:    fillFromNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_firepick_firesight_MatchedRegion_fillFromNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_firepick_firesight_MatchedRegion
 * Method:    createNative
 * Signature: (IIIIDDIF)J
 */
JNIEXPORT jlong JNICALL Java_org_firepick_firesight_MatchedRegion_createNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jdouble, jdouble, jint, jfloat);

/*
 * Class:     org_firepick_firesight_MatchedRegion
 * Method:    releaseNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_firepick_firesight_MatchedRegion_releaseNative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
