/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_firepick_firesight_HoleRecognizer */

#ifndef _Included_org_firepick_firesight_HoleRecognizer
#define _Included_org_firepick_firesight_HoleRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_firepick_firesight_HoleRecognizer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_firepick_firesight_HoleRecognizer_dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_firepick_firesight_HoleRecognizer
 * Method:    init
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_firepick_firesight_HoleRecognizer_init
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_firepick_firesight_HoleRecognizer
 * Method:    _showMatches
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_firepick_firesight_HoleRecognizer__1showMatches
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_firepick_firesight_HoleRecognizer
 * Method:    scan
 * Signature: (JFF)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_firepick_firesight_HoleRecognizer_scan
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
