/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_firepick_firesight_NativeObject */

#ifndef _Included_org_firepick_firesight_NativeObject
#define _Included_org_firepick_firesight_NativeObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_firepick_firesight_NativeObject
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_firepick_firesight_NativeObject_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
